config/routes.rb
Rails.application.routes.draw do
  resources :activities
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable,e and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable


  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @activities = current_user.activities
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    #@activity = Activity.find(params[:id])
  end

  # GET /projects/new
  def new
    @activity = Activity.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @activity = current_user.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = current_user.activities.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:name, :date, :duration, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/activities/_form.html.erb
<div class="wholeform">
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <%= form.label :name_of_activity %>
  <div class="field">
    <%= form.select :name, ['swimming', 'hiking', 'boxing', 'jogging', 'biking', 'swimming', 'rowing', 'skating', 'nordic-walking', 'snowboarding']%>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.time_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<% @activities.each do |activity| %>
  <% link_to activity do %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><% activity.name %></h5>>
      </div>
    </div>
  <% end %>
<% end %>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Duration</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% require 'date' %> 
 

  <tbody>
    <% @activities.each do |activity| %>
    <% %>
      <tr>
        <td><%= activity.name %></td>
        <% if activity.date.present? %>
        <td><%= activity.date.strftime("%d/%m/%Y") %></td>
        <% end %>
        <% if activity.duration.present? %>
        <td><%= activity.duration.strftime("%H:%M") %></td>
        <% end %>
        <td><%= activity.user_id %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity.date.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity.duration.strftime("%H:%M") %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity.user_id %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Welcome to our fitness club!!!</h1>
  </div>
</div>
	
	<!-- Hero section -->
	<section class="hero-section set-bg" data-setbg="img/hero-bg.jpg">
		<div class="container">
			<div class="hero-text">
				<h2>Physical activity</h2>
				<h2>enhances <span>positive energy!</span></h2>
				<a href="" class="site-btn">Join the Gym</a>
			</div>
		</div>
	</section>
	<!-- Hero section end -->

	<!-- Feature section -->
	<section class="feature-section">
		<div class="container">
			<div class="row justify-content-md-center">
				<div class="col-lg-8">
					<div class="section-title text-center">
						<h2>The real <span>workout</span> starts when you want to stop. </h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-004-dumbbell"></i>
						</div>
						<h4>Intense Workouts</h4>
						<p>Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. </p>
					</div>
				</div>
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-031-app-1"></i>
						</div>
						<h4>Intense Workouts</h4>
						<p>Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. </p>
					</div>
				</div>
				<div class="col-md-4">
					<div class="icon-box-item">
						<div class="ib-icon">
							<i class="flaticon-010-podium"></i>
						</div>
						<h4>Intense Workouts</h4>
						<p>Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. </p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Feature section end -->

	<!-- Add section -->
	<section class="add-section set-bg" data-setbg="img/add-bg.jpg">
		<div class="container">
			<div class="row">
				<div class="col-lg-7 ml-auto">
					<div class="add-text">
						<h2>Pay now and get a 25% <span>Discount</span></h2>
						<ul>
							<li><img src="img/check-icon.png" alt="">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
							<li><img src="img/check-icon.png" alt="">Risus commodo viverra maecenas accumsan lacus vel facilisis.</li>
							<li><img src="img/check-icon.png" alt="">Ipsum dolor sit amet, consectetur adipiscing elit, sed do.</li>
						</ul>
						<a href="#" class="site-btn">Become a Member</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Add section end -->

	<!-- Milestones section -->
	<section class="milestones-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="milestone">
						<h2>1374</h2>
						<p>Happy Clients</p>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="milestone">
						<h2>356</h2>
						<p>Strong Bodies</p>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="milestone">
						<h2>57k</h2>
						<p>IG Followers</p>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="milestone">
						<h2>24/7</h2>
						<p>Working Hours</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Milestones section end -->

	<!-- Trainers section -->
	<section class="trainers-section">
		<div class="container">
			<div class="section-title text-center">
				<h2>Meet the <span>Trainers</span></h2>
			</div>
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="trainer-item">
						<div class="trainer-pic">
							<img src="img/trainers/1.jpg" alt="">
						</div>
						<h4>Michael Smith</h4>
						<p>Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum nec sapien.</p>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="trainer-item">
						<div class="trainer-pic">
							<img src="img/trainers/2.jpg" alt="">
						</div>
						<h4>Jessica Black</h4>
						<p>Ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermentum ornare.</p>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="trainer-item">
						<div class="trainer-pic">
							<img src="img/trainers/3.jpg" alt="">
						</div>
						<h4>James Brown</h4>
						<p>Libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum. Donec nec sapien.</p>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="trainer-item">
						<div class="trainer-pic">
							<img src="img/trainers/4.jpg" alt="">
						</div>
						<h4>Paula Carlton</h4>
						<p>Sapien ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermen-tum ornare.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Trainers section end -->

	<!-- BMI section -->
	<section class="bmi-section spad">
		<div class="bmi-bg set-bg" data-setbg="img/bmi-bg.jpg"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-7 ml-auto">
					<div class="section-title mb-0">
						<h2>Calculate your <span>BMI</span></h2>
						<p>Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum nec sapien.Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum nec sapien.</p>
					</div>
					<div class="bmi-calculator-warp">
						<div class="bmi-calculator">
							<div class="row">
								<div class="col-sm-6">
									<input type="text" placeholder="Weight (KG)" id="bmi-weight">
								</div>
								<div class="col-sm-6">
									<input type="text" placeholder="Hight (M)" id="bmi-hight">
								</div>
								<div class="col-sm-6">
									<button class="site-btn" id="bmi-submit">Calculate</button>
								</div>
								<div class="col-sm-6">
									<input type="text" id="bmi-result" readonly>
								</div>
							</div>
							<p>Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum nec sapien.Vivamus libero mauris, bibendum.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- BMI section end -->

	<!-- Newsletter section  -->
	<section class="newsletter-section set-bg" data-setbg="img/newsletter-bg.jpg">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section-title text-white mb-0">
						<h2>Subscribe to <span>newsletter</span></h2>
					</div>
				</div>
				<div class="col-lg-6">
					<form class="newsletter-form">
						<input type="text" placeholder="Your e-mail here">
						<button class="site-btn" type="submit">Subscribe</button>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- Newsletter section end -->

	
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Openclassrooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <!--<%= stylesheet_link_tag 'application', media: 'all' %> -->
    <!--<%= javascript_pack_tag 'application' %> -->


	<!-- Favicon -->
	<link href="http://localhost:3000/img/favicon.ico" rel="shortcut icon"/>


	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="http://localhost:3000/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="http://localhost:3000/css/font-awesome.min.css"/>
	<link rel="stylesheet" href="http://localhost:3000/css/owl.carousel.min.css"/>
	<link rel="stylesheet" href="http://localhost:3000/css/flaticon.css"/>
	<link rel="stylesheet" href="http://localhost:3000/css/slicknav.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="http://localhost:3000/css/style.css"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

	<%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>

</head>
<body>

<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<a href="home.html" class="site-logo">
			<img src="http://localhost:3000/img/logo.png" alt="">
		</a>
		<ul class="main-menu">
			<li>
      <%= link_to('Home', '/') %>
      </li>
      <li>
      <%= link_to('About us', root_path) %>
      </li>        
		<li>
		<%= link_to("Activities", activities_path	) %>
		</li>



		
		<% if user_signed_in? %>
        <li>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>

        </li>
      <% else %>
        <li>
        <%= link_to 'Login', new_user_session_path %>  
        </li>
      <% end %>
     
	 
	  <% if user_signed_in? %>
        <li>
        <%= link_to 'Edit registration', edit_user_registration_path %>
        </li>
      <% else %>
        <li>
        <%= link_to('Register', new_user_registration_path) %>
        </li>
      <% end %>
	  
			<li class="header-right">
				<div class="hr-box">
					<img src="img/location-icon.png" alt="">
					<h6>1525  Amazing Lane, Los Angeles, CA</h6>
				</div>
			</li>
		</ul>
	</header>
	<div class="clearfix"></div>
	<!-- Header section end -->

    



<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
    <!-- Footer section -->
	<footer class="footer-section set-bg" data-setbg="http://localhost:3000/img/footer-bg.jpg">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget">
						<h4>Location</h4>
						<div class="fw-info-box">
							<img src="img/icons/1.png" alt="">
							<div class="fw-info-text">
								<p>1525  Awesome Lane, Los Angeles, CA</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget">
						<h4>Subscriptions</h4>
						<div class="fw-info-box">
							<img src="img/icons/2.png" alt="">
							<div class="fw-info-text">
								<p>+1 (603)535-4592</p>
								<p>+1 (603)535-4556</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget">
						<h4>E-mail</h4>
						<div class="fw-info-box">
              <%= image_tag("img/icons/3.png", :alt => "logo") %> 

							<div class="fw-info-text">
								<p>Contact@xgym.com</p>
								<p>www.xgym.com</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-3 col-sm-6">
					<div class="footer-widget">
						<h4>Social Media</h4>
						<div class="fw-info-box">
							<img src="img/icons/4.png" alt="">
							<div class="social-links">
								<a href="#"><i class="fa fa-pinterest"></i></a>
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 order-2 order-md-1">
					<div class="copyright"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
				</div>
				<div class="col-md-6 order-1 order-md-2">
					<ul class="footer-menu">
						<li><%= link_to('Home', '/') %></li>
						<li><a href="">About Us</a></li>
						<li><%= link_to("Activities", activities_path	) %></li>
						<li><a href="">News</a></li>
						<li><a href="">Contact</a></li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer section end -->
									
	<!--====== Javascripts & Jquery ======-->
	<script src="http://localhost:3000/js/jquery-3.2.1.min.js"></script>
	<script src="http://localhost:3000/js/bootstrap.min.js"></script>
	<script src="http://localhost:3000/js/jquery.slicknav.js"></script>
	<script src="http://localhost:3000/js/owl.carousel.min.js"></script>
	<script src="http://localhost:3000/js/circle-progress.min.js"></script>
	<script src="http://localhost:3000/js/main.js"></script>

  </body>
</html>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Home</a>
          <a class="dropdown-item" href="#">About</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Activities</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" tabindex="-1">Sign up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#" tabindex="-1">Sign in</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>